baseURL = "https://dylanherman.com/"
languageCode = "en-us"
title = "Dylan Herman"
theme = "devise"
relativeURLs = true
enableRobotsTXT = true
enableEmoji = true
copyright = "&copy; Copyright 2020, Dylan Herman"
showFooterCredits = false

# Configuration Features
[params]
  header_title = "Dylan Herman"
  header_subtitle = "Software Engineer"
  home_image = "/img/avatar.png"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "https://github.com/herman5"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://linkedin.com/in/dylanherman"
  [[params.social]]
    fa_icon = "fab fa-stack-overflow fa-1x"
    href = "https://stackoverflow.com/users/845598/anconia"
  [[params.social]]
    fa_icon = "fas fa-envelope fa-1x"
    href = "mailto:d.herman56@gmail.com"
